import type { Metadata } from "next";
import './globals.css'; // Assure-toi que ce fichier existe et est correctement configuré
import NavBarOverlay from './components/NavBar/NavBarOverlay'; // Vérifie le chemin
import ClickScrollBar from "./components/ScrollBar/ClickScrollBar"; // Vérifie le chemin
import Footer from "./components/footer/Footer"; // Vérifie le chemin

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Une description pour la page" />
        <title>Document</title>
      </head>
      <body>
        <ClickScrollBar />
        <NavBarOverlay />
        {children}
        <Footer />
      </body>
    </html>
  );
}
